package com.checkmarx.v7;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-09-13T13:22:08.490+03:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://Checkmarx.com/v7", name = "CxSDKWebServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface CxSDKWebServiceSoap {

    @WebMethod(operationName = "StopDataRetention", action = "http://Checkmarx.com/v7/StopDataRetention")
    @RequestWrapper(localName = "StopDataRetention", targetNamespace = "http://Checkmarx.com/v7", className = "com.checkmarx.v7.StopDataRetention")
    @ResponseWrapper(localName = "StopDataRetentionResponse", targetNamespace = "http://Checkmarx.com/v7", className = "com.checkmarx.v7.StopDataRetentionResponse")
    @WebResult(name = "StopDataRetentionResult", targetNamespace = "http://Checkmarx.com/v7")
    public com.checkmarx.v7.CxWSBasicRepsonse stopDataRetention(
        @WebParam(name = "SessionID", targetNamespace = "http://Checkmarx.com/v7")
        java.lang.String sessionID
    );

    @WebMethod(operationName = "GetTeamLdapGroupsMapping", action = "http://Checkmarx.com/v7/GetTeamLdapGroupsMapping")
    @RequestWrapper(localName = "GetTeamLdapGroupsMapping", targetNamespace = "http://Checkmarx.com/v7", className = "com.checkmarx.v7.GetTeamLdapGroupsMapping")
    @ResponseWrapper(localName = "GetTeamLdapGroupsMappingResponse", targetNamespace = "http://Checkmarx.com/v7", className = "com.checkmarx.v7.GetTeamLdapGroupsMappingResponse")
    @WebResult(name = "GetTeamLdapGroupsMappingResult", targetNamespace = "http://Checkmarx.com/v7")
    public com.checkmarx.v7.CxWSResponseTeamLdapGroupMappingData getTeamLdapGroupsMapping(
        @WebParam(name = "sessionId", targetNamespace = "http://Checkmarx.com/v7")
        java.lang.String sessionId,
        @WebParam(name = "teamId", targetNamespace = "http://Checkmarx.com/v7")
        java.lang.String teamId
    );

    @WebMethod(operationName = "DeleteUser", action = "http://Checkmarx.com/v7/DeleteUser")
    @RequestWrapper(localName = "DeleteUser", targetNamespace = "http://Checkmarx.com/v7", className = "com.checkmarx.v7.DeleteUser")
    @ResponseWrapper(localName = "DeleteUserResponse", targetNamespace = "http://Checkmarx.com/v7", className = "com.checkmarx.v7.DeleteUserResponse")
    @WebResult(name = "DeleteUserResult", targetNamespace = "http://Checkmarx.com/v7")
    public com.checkmarx.v7.CxWSBasicRepsonse deleteUser(
        @WebParam(name = "sessionID", targetNamespace = "http://Checkmarx.com/v7")
        java.lang.String sessionID,
        @WebParam(name = "userID", targetNamespace = "http://Checkmarx.com/v7")
        int userID
    );

    @WebMethod(operationName = "UpdateProjectIncrementalConfiguration", action = "http://Checkmarx.com/v7/UpdateProjectIncrementalConfiguration")
    @RequestWrapper(localName = "UpdateProjectIncrementalConfiguration", targetNamespace = "http://Checkmarx.com/v7", className = "com.checkmarx.v7.UpdateProjectIncrementalConfiguration")
    @ResponseWrapper(localName = "UpdateProjectIncrementalConfigurationResponse", targetNamespace = "http://Checkmarx.com/v7", className = "com.checkmarx.v7.UpdateProjectIncrementalConfigurationResponse")
    @WebResult(name = "UpdateProjectIncrementalConfigurationResult", targetNamespace = "http://Checkmarx.com/v7")
    public com.checkmarx.v7.CxWSBasicRepsonse updateProjectIncrementalConfiguration(
        @WebParam(name = "sessionID", targetNamespace = "http://Checkmarx.com/v7")
        java.lang.String sessionID,
        @WebParam(name = "projectID", targetNamespace = "http://Checkmarx.com/v7")
        long projectID,
        @WebParam(name = "projectConfiguration", targetNamespace = "http://Checkmarx.com/v7")
        com.checkmarx.v7.ProjectConfiguration projectConfiguration
    );

    @WebMethod(operationName = "GetProjectsDisplayData", action = "http://Checkmarx.com/v7/GetProjectsDisplayData")
    @RequestWrapper(localName = "GetProjectsDisplayData", targetNamespace = "http://Checkmarx.com/v7", className = "com.checkmarx.v7.GetProjectsDisplayData")
    @ResponseWrapper(localName = "GetProjectsDisplayDataResponse", targetNamespace = "http://Checkmarx.com/v7", className = "com.checkmarx.v7.GetProjectsDisplayDataResponse")
    @WebResult(name = "GetProjectsDisplayDataResult", targetNamespace = "http://Checkmarx.com/v7")
    public com.checkmarx.v7.CxWSResponseProjectsDisplayData getProjectsDisplayData(
        @WebParam(name = "sessionID", targetNamespace = "http://Checkmarx.com/v7")
        java.lang.String sessionID
    );

    @WebMethod(operationName = "DeleteProjects", action = "http://Checkmarx.com/v7/DeleteProjects")
    @RequestWrapper(localName = "DeleteProjects", targetNamespace = "http://Checkmarx.com/v7", className = "com.checkmarx.v7.DeleteProjects")
    @ResponseWrapper(localName = "DeleteProjectsResponse", targetNamespace = "http://Checkmarx.com/v7", className = "com.checkmarx.v7.DeleteProjectsResponse")
    @WebResult(name = "DeleteProjectsResult", targetNamespace = "http://Checkmarx.com/v7")
    public com.checkmarx.v7.CxWSBasicRepsonse deleteProjects(
        @WebParam(name = "sessionID", targetNamespace = "http://Checkmarx.com/v7")
        java.lang.String sessionID,
        @WebParam(name = "projectIDs", targetNamespace = "http://Checkmarx.com/v7")
        com.checkmarx.v7.ArrayOfLong projectIDs
    );

    @WebMethod(operationName = "GetScanReportStatus", action = "http://Checkmarx.com/v7/GetScanReportStatus")
    @RequestWrapper(localName = "GetScanReportStatus", targetNamespace = "http://Checkmarx.com/v7", className = "com.checkmarx.v7.GetScanReportStatus")
    @ResponseWrapper(localName = "GetScanReportStatusResponse", targetNamespace = "http://Checkmarx.com/v7", className = "com.checkmarx.v7.GetScanReportStatusResponse")
    @WebResult(name = "GetScanReportStatusResult", targetNamespace = "http://Checkmarx.com/v7")
    public com.checkmarx.v7.CxWSReportStatusResponse getScanReportStatus(
        @WebParam(name = "SessionID", targetNamespace = "http://Checkmarx.com/v7")
        java.lang.String sessionID,
        @WebParam(name = "ReportID", targetNamespace = "http://Checkmarx.com/v7")
        long reportID
    );

    @WebMethod(operationName = "UpdateProjectConfiguration", action = "http://Checkmarx.com/v7/UpdateProjectConfiguration")
    @RequestWrapper(localName = "UpdateProjectConfiguration", targetNamespace = "http://Checkmarx.com/v7", className = "com.checkmarx.v7.UpdateProjectConfiguration")
    @ResponseWrapper(localName = "UpdateProjectConfigurationResponse", targetNamespace = "http://Checkmarx.com/v7", className = "com.checkmarx.v7.UpdateProjectConfigurationResponse")
    @WebResult(name = "UpdateProjectConfigurationResult", targetNamespace = "http://Checkmarx.com/v7")
    public com.checkmarx.v7.CxWSBasicRepsonse updateProjectConfiguration(
        @WebParam(name = "sessionID", targetNamespace = "http://Checkmarx.com/v7")
        java.lang.String sessionID,
        @WebParam(name = "projectID", targetNamespace = "http://Checkmarx.com/v7")
        long projectID,
        @WebParam(name = "projectConfiguration", targetNamespace = "http://Checkmarx.com/v7")
        com.checkmarx.v7.ProjectConfiguration projectConfiguration
    );

    @WebMethod(operationName = "ScanWithScheduling", action = "http://Checkmarx.com/v7/ScanWithScheduling")
    @RequestWrapper(localName = "ScanWithScheduling", targetNamespace = "http://Checkmarx.com/v7", className = "com.checkmarx.v7.ScanWithScheduling")
    @ResponseWrapper(localName = "ScanWithSchedulingResponse", targetNamespace = "http://Checkmarx.com/v7", className = "com.checkmarx.v7.ScanWithSchedulingResponse")
    @WebResult(name = "ScanWithSchedulingResult", targetNamespace = "http://Checkmarx.com/v7")
    public com.checkmarx.v7.CxWSResponseRunID scanWithScheduling(
        @WebParam(name = "sessionId", targetNamespace = "http://Checkmarx.com/v7")
        java.lang.String sessionId,
        @WebParam(name = "args", targetNamespace = "http://Checkmarx.com/v7")
        com.checkmarx.v7.CliScanArgs args,
        @WebParam(name = "schedulingData", targetNamespace = "http://Checkmarx.com/v7")
        java.lang.String schedulingData
    );

    @WebMethod(operationName = "GetAllUsers", action = "http://Checkmarx.com/v7/GetAllUsers")
    @RequestWrapper(localName = "GetAllUsers", targetNamespace = "http://Checkmarx.com/v7", className = "com.checkmarx.v7.GetAllUsers")
    @ResponseWrapper(localName = "GetAllUsersResponse", targetNamespace = "http://Checkmarx.com/v7", className = "com.checkmarx.v7.GetAllUsersResponse")
    @WebResult(name = "GetAllUsersResult", targetNamespace = "http://Checkmarx.com/v7")
    public com.checkmarx.v7.CxWSResponseUserData getAllUsers(
        @WebParam(name = "sessionID", targetNamespace = "http://Checkmarx.com/v7")
        java.lang.String sessionID
    );

    @WebMethod(operationName = "Logout", action = "http://Checkmarx.com/v7/Logout")
    @RequestWrapper(localName = "Logout", targetNamespace = "http://Checkmarx.com/v7", className = "com.checkmarx.v7.Logout")
    @ResponseWrapper(localName = "LogoutResponse", targetNamespace = "http://Checkmarx.com/v7", className = "com.checkmarx.v7.LogoutResponse")
    @WebResult(name = "LogoutResult", targetNamespace = "http://Checkmarx.com/v7")
    public com.checkmarx.v7.CxWSBasicRepsonse logout(
        @WebParam(name = "sessionID", targetNamespace = "http://Checkmarx.com/v7")
        java.lang.String sessionID
    );

    @WebMethod(operationName = "CancelScan", action = "http://Checkmarx.com/v7/CancelScan")
    @RequestWrapper(localName = "CancelScan", targetNamespace = "http://Checkmarx.com/v7", className = "com.checkmarx.v7.CancelScan")
    @ResponseWrapper(localName = "CancelScanResponse", targetNamespace = "http://Checkmarx.com/v7", className = "com.checkmarx.v7.CancelScanResponse")
    @WebResult(name = "CancelScanResult", targetNamespace = "http://Checkmarx.com/v7")
    public com.checkmarx.v7.CxWSBasicRepsonse cancelScan(
        @WebParam(name = "sessionID", targetNamespace = "http://Checkmarx.com/v7")
        java.lang.String sessionID,
        @WebParam(name = "RunId", targetNamespace = "http://Checkmarx.com/v7")
        java.lang.String runId
    );

    @WebMethod(operationName = "GetScansDisplayDataForAllProjects", action = "http://Checkmarx.com/v7/GetScansDisplayDataForAllProjects")
    @RequestWrapper(localName = "GetScansDisplayDataForAllProjects", targetNamespace = "http://Checkmarx.com/v7", className = "com.checkmarx.v7.GetScansDisplayDataForAllProjects")
    @ResponseWrapper(localName = "GetScansDisplayDataForAllProjectsResponse", targetNamespace = "http://Checkmarx.com/v7", className = "com.checkmarx.v7.GetScansDisplayDataForAllProjectsResponse")
    @WebResult(name = "GetScansDisplayDataForAllProjectsResult", targetNamespace = "http://Checkmarx.com/v7")
    public com.checkmarx.v7.CxWSResponseScansDisplayData getScansDisplayDataForAllProjects(
        @WebParam(name = "sessionID", targetNamespace = "http://Checkmarx.com/v7")
        java.lang.String sessionID
    );

    @WebMethod(operationName = "DeleteScans", action = "http://Checkmarx.com/v7/DeleteScans")
    @RequestWrapper(localName = "DeleteScans", targetNamespace = "http://Checkmarx.com/v7", className = "com.checkmarx.v7.DeleteScans")
    @ResponseWrapper(localName = "DeleteScansResponse", targetNamespace = "http://Checkmarx.com/v7", className = "com.checkmarx.v7.DeleteScansResponse")
    @WebResult(name = "DeleteScansResult", targetNamespace = "http://Checkmarx.com/v7")
    public com.checkmarx.v7.CxWSBasicRepsonse deleteScans(
        @WebParam(name = "sessionID", targetNamespace = "http://Checkmarx.com/v7")
        java.lang.String sessionID,
        @WebParam(name = "scanIDs", targetNamespace = "http://Checkmarx.com/v7")
        com.checkmarx.v7.ArrayOfLong scanIDs
    );

    @WebMethod(operationName = "GetPresetList", action = "http://Checkmarx.com/v7/GetPresetList")
    @RequestWrapper(localName = "GetPresetList", targetNamespace = "http://Checkmarx.com/v7", className = "com.checkmarx.v7.GetPresetList")
    @ResponseWrapper(localName = "GetPresetListResponse", targetNamespace = "http://Checkmarx.com/v7", className = "com.checkmarx.v7.GetPresetListResponse")
    @WebResult(name = "GetPresetListResult", targetNamespace = "http://Checkmarx.com/v7")
    public com.checkmarx.v7.CxWSResponsePresetList getPresetList(
        @WebParam(name = "SessionID", targetNamespace = "http://Checkmarx.com/v7")
        java.lang.String sessionID
    );

    @WebMethod(operationName = "Login", action = "http://Checkmarx.com/v7/Login")
    @RequestWrapper(localName = "Login", targetNamespace = "http://Checkmarx.com/v7", className = "com.checkmarx.v7.Login")
    @ResponseWrapper(localName = "LoginResponse", targetNamespace = "http://Checkmarx.com/v7", className = "com.checkmarx.v7.LoginResponse")
    @WebResult(name = "LoginResult", targetNamespace = "http://Checkmarx.com/v7")
    public com.checkmarx.v7.CxWSResponseLoginData login(
        @WebParam(name = "applicationCredentials", targetNamespace = "http://Checkmarx.com/v7")
        com.checkmarx.v7.Credentials applicationCredentials,
        @WebParam(name = "lcid", targetNamespace = "http://Checkmarx.com/v7")
        int lcid
    );

    @WebMethod(operationName = "SetTeamLdapGroupsMapping", action = "http://Checkmarx.com/v7/SetTeamLdapGroupsMapping")
    @RequestWrapper(localName = "SetTeamLdapGroupsMapping", targetNamespace = "http://Checkmarx.com/v7", className = "com.checkmarx.v7.SetTeamLdapGroupsMapping")
    @ResponseWrapper(localName = "SetTeamLdapGroupsMappingResponse", targetNamespace = "http://Checkmarx.com/v7", className = "com.checkmarx.v7.SetTeamLdapGroupsMappingResponse")
    @WebResult(name = "SetTeamLdapGroupsMappingResult", targetNamespace = "http://Checkmarx.com/v7")
    public com.checkmarx.v7.CxWSBasicRepsonse setTeamLdapGroupsMapping(
        @WebParam(name = "sessionId", targetNamespace = "http://Checkmarx.com/v7")
        java.lang.String sessionId,
        @WebParam(name = "teamId", targetNamespace = "http://Checkmarx.com/v7")
        java.lang.String teamId,
        @WebParam(name = "ldapGroups", targetNamespace = "http://Checkmarx.com/v7")
        com.checkmarx.v7.ArrayOfCxWSLdapGroupMapping ldapGroups
    );

    @WebMethod(operationName = "ExecuteDataRetention", action = "http://Checkmarx.com/v7/ExecuteDataRetention")
    @RequestWrapper(localName = "ExecuteDataRetention", targetNamespace = "http://Checkmarx.com/v7", className = "com.checkmarx.v7.ExecuteDataRetention")
    @ResponseWrapper(localName = "ExecuteDataRetentionResponse", targetNamespace = "http://Checkmarx.com/v7", className = "com.checkmarx.v7.ExecuteDataRetentionResponse")
    @WebResult(name = "ExecuteDataRetentionResult", targetNamespace = "http://Checkmarx.com/v7")
    public com.checkmarx.v7.CxWSBasicRepsonse executeDataRetention(
        @WebParam(name = "SessionID", targetNamespace = "http://Checkmarx.com/v7")
        java.lang.String sessionID,
        @WebParam(name = "dataRetentionConfiguration", targetNamespace = "http://Checkmarx.com/v7")
        com.checkmarx.v7.CxDataRetentionConfiguration dataRetentionConfiguration
    );

    @WebMethod(operationName = "GetProjectScannedDisplayData", action = "http://Checkmarx.com/v7/GetProjectScannedDisplayData")
    @RequestWrapper(localName = "GetProjectScannedDisplayData", targetNamespace = "http://Checkmarx.com/v7", className = "com.checkmarx.v7.GetProjectScannedDisplayData")
    @ResponseWrapper(localName = "GetProjectScannedDisplayDataResponse", targetNamespace = "http://Checkmarx.com/v7", className = "com.checkmarx.v7.GetProjectScannedDisplayDataResponse")
    @WebResult(name = "GetProjectScannedDisplayDataResult", targetNamespace = "http://Checkmarx.com/v7")
    public com.checkmarx.v7.CxWSResponseProjectScannedDisplayData getProjectScannedDisplayData(
        @WebParam(name = "sessionID", targetNamespace = "http://Checkmarx.com/v7")
        java.lang.String sessionID
    );

    @WebMethod(operationName = "GetProjectConfiguration", action = "http://Checkmarx.com/v7/GetProjectConfiguration")
    @RequestWrapper(localName = "GetProjectConfiguration", targetNamespace = "http://Checkmarx.com/v7", className = "com.checkmarx.v7.GetProjectConfiguration")
    @ResponseWrapper(localName = "GetProjectConfigurationResponse", targetNamespace = "http://Checkmarx.com/v7", className = "com.checkmarx.v7.GetProjectConfigurationResponse")
    @WebResult(name = "GetProjectConfigurationResult", targetNamespace = "http://Checkmarx.com/v7")
    public com.checkmarx.v7.CxWSResponseProjectConfig getProjectConfiguration(
        @WebParam(name = "sessionID", targetNamespace = "http://Checkmarx.com/v7")
        java.lang.String sessionID,
        @WebParam(name = "projectID", targetNamespace = "http://Checkmarx.com/v7")
        long projectID
    );

    @WebMethod(operationName = "GetAssociatedGroupsList", action = "http://Checkmarx.com/v7/GetAssociatedGroupsList")
    @RequestWrapper(localName = "GetAssociatedGroupsList", targetNamespace = "http://Checkmarx.com/v7", className = "com.checkmarx.v7.GetAssociatedGroupsList")
    @ResponseWrapper(localName = "GetAssociatedGroupsListResponse", targetNamespace = "http://Checkmarx.com/v7", className = "com.checkmarx.v7.GetAssociatedGroupsListResponse")
    @WebResult(name = "GetAssociatedGroupsListResult", targetNamespace = "http://Checkmarx.com/v7")
    public com.checkmarx.v7.CxWSResponseGroupList getAssociatedGroupsList(
        @WebParam(name = "SessionID", targetNamespace = "http://Checkmarx.com/v7")
        java.lang.String sessionID
    );

    @WebMethod(operationName = "GetStatusOfSingleScan", action = "http://Checkmarx.com/v7/GetStatusOfSingleScan")
    @RequestWrapper(localName = "GetStatusOfSingleScan", targetNamespace = "http://Checkmarx.com/v7", className = "com.checkmarx.v7.GetStatusOfSingleScan")
    @ResponseWrapper(localName = "GetStatusOfSingleScanResponse", targetNamespace = "http://Checkmarx.com/v7", className = "com.checkmarx.v7.GetStatusOfSingleScanResponse")
    @WebResult(name = "GetStatusOfSingleScanResult", targetNamespace = "http://Checkmarx.com/v7")
    public com.checkmarx.v7.CxWSResponseScanStatus getStatusOfSingleScan(
        @WebParam(name = "sessionID", targetNamespace = "http://Checkmarx.com/v7")
        java.lang.String sessionID,
        @WebParam(name = "runId", targetNamespace = "http://Checkmarx.com/v7")
        java.lang.String runId
    );

    @WebMethod(operationName = "GetScanReport", action = "http://Checkmarx.com/v7/GetScanReport")
    @RequestWrapper(localName = "GetScanReport", targetNamespace = "http://Checkmarx.com/v7", className = "com.checkmarx.v7.GetScanReport")
    @ResponseWrapper(localName = "GetScanReportResponse", targetNamespace = "http://Checkmarx.com/v7", className = "com.checkmarx.v7.GetScanReportResponse")
    @WebResult(name = "GetScanReportResult", targetNamespace = "http://Checkmarx.com/v7")
    public com.checkmarx.v7.CxWSResponseScanResults getScanReport(
        @WebParam(name = "SessionID", targetNamespace = "http://Checkmarx.com/v7")
        java.lang.String sessionID,
        @WebParam(name = "ReportID", targetNamespace = "http://Checkmarx.com/v7")
        long reportID
    );

    @WebMethod(operationName = "GetConfigurationSetList", action = "http://Checkmarx.com/v7/GetConfigurationSetList")
    @RequestWrapper(localName = "GetConfigurationSetList", targetNamespace = "http://Checkmarx.com/v7", className = "com.checkmarx.v7.GetConfigurationSetList")
    @ResponseWrapper(localName = "GetConfigurationSetListResponse", targetNamespace = "http://Checkmarx.com/v7", className = "com.checkmarx.v7.GetConfigurationSetListResponse")
    @WebResult(name = "GetConfigurationSetListResult", targetNamespace = "http://Checkmarx.com/v7")
    public com.checkmarx.v7.CxWSResponseConfigSetList getConfigurationSetList(
        @WebParam(name = "SessionID", targetNamespace = "http://Checkmarx.com/v7")
        java.lang.String sessionID
    );

    @WebMethod(operationName = "UpdateScanComment", action = "http://Checkmarx.com/v7/UpdateScanComment")
    @RequestWrapper(localName = "UpdateScanComment", targetNamespace = "http://Checkmarx.com/v7", className = "com.checkmarx.v7.UpdateScanComment")
    @ResponseWrapper(localName = "UpdateScanCommentResponse", targetNamespace = "http://Checkmarx.com/v7", className = "com.checkmarx.v7.UpdateScanCommentResponse")
    @WebResult(name = "UpdateScanCommentResult", targetNamespace = "http://Checkmarx.com/v7")
    public com.checkmarx.v7.CxWSBasicRepsonse updateScanComment(
        @WebParam(name = "sessionID", targetNamespace = "http://Checkmarx.com/v7")
        java.lang.String sessionID,
        @WebParam(name = "ScanID", targetNamespace = "http://Checkmarx.com/v7")
        long scanID,
        @WebParam(name = "Comment", targetNamespace = "http://Checkmarx.com/v7")
        java.lang.String comment
    );

    @WebMethod(operationName = "GetScanSummary", action = "http://Checkmarx.com/v7/GetScanSummary")
    @RequestWrapper(localName = "GetScanSummary", targetNamespace = "http://Checkmarx.com/v7", className = "com.checkmarx.v7.GetScanSummary")
    @ResponseWrapper(localName = "GetScanSummaryResponse", targetNamespace = "http://Checkmarx.com/v7", className = "com.checkmarx.v7.GetScanSummaryResponse")
    @WebResult(name = "GetScanSummaryResult", targetNamespace = "http://Checkmarx.com/v7")
    public com.checkmarx.v7.CxWSResponseScanSummary getScanSummary(
        @WebParam(name = "SessionID", targetNamespace = "http://Checkmarx.com/v7")
        java.lang.String sessionID,
        @WebParam(name = "ScanID", targetNamespace = "http://Checkmarx.com/v7")
        long scanID
    );

    @WebMethod(operationName = "ScanWithOriginName", action = "http://Checkmarx.com/v7/ScanWithOriginName")
    @RequestWrapper(localName = "ScanWithOriginName", targetNamespace = "http://Checkmarx.com/v7", className = "com.checkmarx.v7.ScanWithOriginName")
    @ResponseWrapper(localName = "ScanWithOriginNameResponse", targetNamespace = "http://Checkmarx.com/v7", className = "com.checkmarx.v7.ScanWithOriginNameResponse")
    @WebResult(name = "ScanWithOriginNameResult", targetNamespace = "http://Checkmarx.com/v7")
    public com.checkmarx.v7.CxWSResponseRunID scanWithOriginName(
        @WebParam(name = "sessionId", targetNamespace = "http://Checkmarx.com/v7")
        java.lang.String sessionId,
        @WebParam(name = "args", targetNamespace = "http://Checkmarx.com/v7")
        com.checkmarx.v7.CliScanArgs args,
        @WebParam(name = "origName", targetNamespace = "http://Checkmarx.com/v7")
        java.lang.String origName
    );

    @WebMethod(operationName = "Scan", action = "http://Checkmarx.com/v7/Scan")
    @RequestWrapper(localName = "Scan", targetNamespace = "http://Checkmarx.com/v7", className = "com.checkmarx.v7.Scan")
    @ResponseWrapper(localName = "ScanResponse", targetNamespace = "http://Checkmarx.com/v7", className = "com.checkmarx.v7.ScanResponse")
    @WebResult(name = "ScanResult", targetNamespace = "http://Checkmarx.com/v7")
    public com.checkmarx.v7.CxWSResponseRunID scan(
        @WebParam(name = "sessionId", targetNamespace = "http://Checkmarx.com/v7")
        java.lang.String sessionId,
        @WebParam(name = "args", targetNamespace = "http://Checkmarx.com/v7")
        com.checkmarx.v7.CliScanArgs args
    );

    @WebMethod(operationName = "ScanWithSchedulingWithCron", action = "http://Checkmarx.com/v7/ScanWithSchedulingWithCron")
    @RequestWrapper(localName = "ScanWithSchedulingWithCron", targetNamespace = "http://Checkmarx.com/v7", className = "com.checkmarx.v7.ScanWithSchedulingWithCron")
    @ResponseWrapper(localName = "ScanWithSchedulingWithCronResponse", targetNamespace = "http://Checkmarx.com/v7", className = "com.checkmarx.v7.ScanWithSchedulingWithCronResponse")
    @WebResult(name = "ScanWithSchedulingWithCronResult", targetNamespace = "http://Checkmarx.com/v7")
    public com.checkmarx.v7.CxWSResponseRunID scanWithSchedulingWithCron(
        @WebParam(name = "sessionId", targetNamespace = "http://Checkmarx.com/v7")
        java.lang.String sessionId,
        @WebParam(name = "args", targetNamespace = "http://Checkmarx.com/v7")
        com.checkmarx.v7.CliScanArgs args,
        @WebParam(name = "cronString", targetNamespace = "http://Checkmarx.com/v7")
        java.lang.String cronString,
        @WebParam(name = "utcEpochStartTime", targetNamespace = "http://Checkmarx.com/v7")
        long utcEpochStartTime,
        @WebParam(name = "utcEpochEndTime", targetNamespace = "http://Checkmarx.com/v7")
        long utcEpochEndTime
    );

    @WebMethod(operationName = "CreateScanReport", action = "http://Checkmarx.com/v7/CreateScanReport")
    @RequestWrapper(localName = "CreateScanReport", targetNamespace = "http://Checkmarx.com/v7", className = "com.checkmarx.v7.CreateScanReport")
    @ResponseWrapper(localName = "CreateScanReportResponse", targetNamespace = "http://Checkmarx.com/v7", className = "com.checkmarx.v7.CreateScanReportResponse")
    @WebResult(name = "CreateScanReportResult", targetNamespace = "http://Checkmarx.com/v7")
    public com.checkmarx.v7.CxWSCreateReportResponse createScanReport(
        @WebParam(name = "sessionID", targetNamespace = "http://Checkmarx.com/v7")
        java.lang.String sessionID,
        @WebParam(name = "reportRequest", targetNamespace = "http://Checkmarx.com/v7")
        com.checkmarx.v7.CxWSReportRequest reportRequest
    );
}
